# Generated by Django 5.1.2 on 2024-11-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.createform')),
            ],
        ),
    ]
